apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: westcluster-es-elastic-user
data:
  elastic: ZWxhc3RpYw==
---
apiVersion: v1
kind: Secret
metadata:
  name: eck-trial-license
  namespace: elastic-system
  labels:
    license.k8s.elastic.co/type: enterprise_trial
  annotations:
    elastic.co/eula: accepted 
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: westcluster
spec:
  version: 9.0.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
  http:
    service:
      spec:
        type: LoadBalancer
  transport:
    service:
      spec:
        type: LoadBalancer